### ISSUE TITLE
Chapter 8 listing 8.1 causes error

### ISSUE THREAD

**Issue by ghost** [bwdbooks/nodejs-mongodb-angularjs-web-development#2]
On chapter 8 after running

```
node socket_client.js
```

I get the error

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

**Comment by ghost** [comment]
Duh, i had to actually run the server created a bit later in the chapter.

**Comment by GitHubKen** [comment]
Which server because I'm running into the same error as I run other .js files, especially the word_init.js?
