### ISSUE TITLE
I get a throw er:

### ISSUE THREAD

**Issue by jmsykes15** [bwdbooks/nodejs-mongodb-angularjs-web-development#4]
When I try to run the code I get this error:

node auth_server.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Function.app.listen (/home/ubuntu/htdocs/joolip/node_modules/express/lib/application.js:532:24)
    at Object.<anonymous> (/home/ubuntu/htdocs/joolip/auth_server.js:27:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by jmsykes15** [comment]
This error is received on assignment: 26 google auth.  I don't get it on the 26.  I have tried using auth_google.js also.

**Comment by mastash3ff** [comment]
Also receive the same thing

**Comment by mastash3ff** [comment]
Resolve previous problem by 'npm update'  Now getting:

mastash3ff@home:~/playground/MEAN/nodejs-mongodb-angularjs-web-development/ch26$ node auth_server.js 
express-session deprecated undefined resave option; provide resave option auth_server.js:16:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option auth_server.js:16:9

/home/mastash3ff/playground/MEAN/nodejs-mongodb-angularjs-web-development/node_modules/connect-mongo/lib/connect-mongo.js:133
          throw err;
                ^
MongoError: cannot connect to server

**Comment by GitHubKen** [comment]
I get this error:

node auth_server.js

express-session deprecated undefined resave option; provide resave option auth_server.js:16:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option auth_server
.js:16:9
/home/githubken/nodejs-mongodb-angularjs-web-development/ch26/auth_server.js:25
app.listen(80);pp.listen(80);
                       ^
ReferenceError: pp is not defined
    at Object.<anonymous> (/home/githubken/nodejs-mongodb-angularjs-web-development/ch26/auth_serve
r.js:25:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
